// Automatically generated by pegomock. DO NOT EDIT!
// Source: webhooks.go

package mocks

import (
	logging "github.com/hootsuite/atlantis/server/logging"
	pegomock "github.com/petergtz/pegomock"
	"reflect"
)

type MockWebhooksSender struct {
	fail func(message string, callerSkip ...int)
}

func NewMockWebhooksSender() *MockWebhooksSender {
	return &MockWebhooksSender{fail: pegomock.GlobalFailHandler}
}

func (mock *MockWebhooksSender) Send(log *logging.SimpleLogger, result ApplyResult) {
	params := []pegomock.Param{log, result}
	pegomock.GetGenericMockFrom(mock).Invoke("Send", params, []reflect.Type{})
}

func (mock *MockWebhooksSender) VerifyWasCalledOnce() *VerifierWebhooksSender {
	return &VerifierWebhooksSender{mock, pegomock.Times(1), nil}
}

func (mock *MockWebhooksSender) VerifyWasCalled(invocationCountMatcher pegomock.Matcher) *VerifierWebhooksSender {
	return &VerifierWebhooksSender{mock, invocationCountMatcher, nil}
}

func (mock *MockWebhooksSender) VerifyWasCalledInOrder(invocationCountMatcher pegomock.Matcher, inOrderContext *pegomock.InOrderContext) *VerifierWebhooksSender {
	return &VerifierWebhooksSender{mock, invocationCountMatcher, inOrderContext}
}

type VerifierWebhooksSender struct {
	mock                   *MockWebhooksSender
	invocationCountMatcher pegomock.Matcher
	inOrderContext         *pegomock.InOrderContext
}

func (verifier *VerifierWebhooksSender) Send(log *logging.SimpleLogger, result ApplyResult) *WebhooksSender_Send_OngoingVerification {
	params := []pegomock.Param{log, result}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "Send", params)
	return &WebhooksSender_Send_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type WebhooksSender_Send_OngoingVerification struct {
	mock              *MockWebhooksSender
	methodInvocations []pegomock.MethodInvocation
}

func (c *WebhooksSender_Send_OngoingVerification) GetCapturedArguments() (*logging.SimpleLogger, ApplyResult) {
	log, result := c.GetAllCapturedArguments()
	return log[len(log)-1], result[len(result)-1]
}

func (c *WebhooksSender_Send_OngoingVerification) GetAllCapturedArguments() (_param0 []*logging.SimpleLogger, _param1 []ApplyResult) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]*logging.SimpleLogger, len(params[0]))
		for u, param := range params[0] {
			_param0[u] = param.(*logging.SimpleLogger)
		}
		_param1 = make([]ApplyResult, len(params[1]))
		for u, param := range params[1] {
			_param1[u] = param.(ApplyResult)
		}
	}
	return
}

type MockWebhookSender struct {
	fail func(message string, callerSkip ...int)
}

func NewMockWebhookSender() *MockWebhookSender {
	return &MockWebhookSender{fail: pegomock.GlobalFailHandler}
}

func (mock *MockWebhookSender) Send(_param0 ApplyResult) error {
	params := []pegomock.Param{_param0}
	result := pegomock.GetGenericMockFrom(mock).Invoke("Send", params, []reflect.Type{reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(error)
		}
	}
	return ret0
}

func (mock *MockWebhookSender) VerifyWasCalledOnce() *VerifierWebhookSender {
	return &VerifierWebhookSender{mock, pegomock.Times(1), nil}
}

func (mock *MockWebhookSender) VerifyWasCalled(invocationCountMatcher pegomock.Matcher) *VerifierWebhookSender {
	return &VerifierWebhookSender{mock, invocationCountMatcher, nil}
}

func (mock *MockWebhookSender) VerifyWasCalledInOrder(invocationCountMatcher pegomock.Matcher, inOrderContext *pegomock.InOrderContext) *VerifierWebhookSender {
	return &VerifierWebhookSender{mock, invocationCountMatcher, inOrderContext}
}

type VerifierWebhookSender struct {
	mock                   *MockWebhookSender
	invocationCountMatcher pegomock.Matcher
	inOrderContext         *pegomock.InOrderContext
}

func (verifier *VerifierWebhookSender) Send(_param0 ApplyResult) *WebhookSender_Send_OngoingVerification {
	params := []pegomock.Param{_param0}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "Send", params)
	return &WebhookSender_Send_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type WebhookSender_Send_OngoingVerification struct {
	mock              *MockWebhookSender
	methodInvocations []pegomock.MethodInvocation
}

func (c *WebhookSender_Send_OngoingVerification) GetCapturedArguments() ApplyResult {
	_param0 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1]
}

func (c *WebhookSender_Send_OngoingVerification) GetAllCapturedArguments() (_param0 []ApplyResult) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]ApplyResult, len(params[0]))
		for u, param := range params[0] {
			_param0[u] = param.(ApplyResult)
		}
	}
	return
}
