baseURL = "http://atlantis.run"
languageCode = "en-us"
title = "Atlantis - A unified workflow for collaborating on Terraform through GitHub"
theme = "kube"
description = "A unified workflow for collaborating on Terraform through GitHub"
Paginate = 4
[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "FAQ"
    weight = -100
    url = "/faq/"
[[menu.main]]
    name = "Demo"
    weight = 100
    url = "https://www.youtube.com/watch?v=TmIPWda0IKg"
